baseURL = "https://lab.wcloud.sh/"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
buildDrafts = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
      name = "tags"
      weight = 100

    [[related.indices]]
      name = "categories"
      weight = 100

    [[related.indices]]
      name = "series"
      weight = 50

    [[related.indices]]
      name = "date"
      weight = 10
