[[main]]
  name = "Infrastructure"
  pageRef = "infrastructure"
  weight = 1

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 2

[[main]]
  name = "Journal"
  pageRef = "posts"
  weight = 3

[[main]]
  name = "About"
  pageRef = "about"
  weight = 4

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 5
