colorScheme = "oled"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  sharingLinks = []

[list]
  showBreadcrumbs = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true

[term]
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[umamiAnalytics]
  websiteid = "3025d29c-4520-445c-b40d-22f801a6c874"
  domain = "cloud.umami.is"
